### ISSUE TITLE
Variants with Multiple Prices

### ISSUE THREAD

**Issue by CLloyd24** [carolineschnapp/customizr#1]
I'm really bummed that Spotify only allows for three variants but was happy to find this plugin. I have one concern though. If I understand correctly though, even with customizr you must use Shopify's built-in variants for options with different prices. If correct this means that you can't have a product with more than three differently priced variants. Is this correct?

If not is there a quick tutorial on how to achieve this?

Thank you.

Chris

**Comment by carolineschnapp** [comment]
That's correct.
